import {createClient} from "@supabase/supabase-js";
import {readFileSync} from "node:fs";
import assert from "node:assert/strict";
import {z} from "zod";
import {newDraft,publicEventSchema} from "../src/features/events/contracts";
import type {Database} from "../src/server/db/database.types";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;const ref=process.env.SEED_PROJECT_REF;
if(process.env.APP_ENV!=="development"||process.env.VERCEL_ENV||!url||!key||!ref||new URL(url).hostname!==ref+".supabase.co"||!process.argv.includes("--confirm="+ref))throw new Error("Verification refused: select a development project explicitly.");
const fixture=JSON.parse(readFileSync(".test-fixture.json","utf8")) as {email:string;password:string};
if(!fixture.email.endsWith("@example.test"))throw new Error("Use a disposable example.test identity.");
const db=createClient<Database>(url,key,{auth:{storageKey:crypto.randomUUID(),persistSession:false,autoRefreshToken:false},global:{fetch:(input,init)=>fetch(input,{...init,signal:AbortSignal.timeout(20000)})}});
const anon=createClient<Database>(url,key,{auth:{storageKey:crypto.randomUUID(),persistSession:false,autoRefreshToken:false},global:{fetch:(input,init)=>fetch(input,{...init,signal:AbortSignal.timeout(20000)})}});
console.info("Checking authentication...");
const {error:signInError}=await db.auth.signInWithPassword(fixture);assert.equal(signInError,null);
console.info("Creating concurrency fixture...");
const draft=newDraft();draft.basics.name="Concurrency verification";draft.basics.slug="concurrency-"+crypto.randomUUID();draft.basics.description="A synthetic concurrency verification fixture.";draft.basics.location="Test venue";
const type=crypto.randomUUID();draft.config.types=[{id:type,name:"One place",description:"",capacity:1,approval:false}];
const {data:saved,error:createError}=await db.rpc("create_event",{payload:draft});assert.equal(createError,null);
const event=z.object({id:z.uuid(),revision:z.number()}).parse(saved);
const {data:version,error:publishError}=await db.rpc("publish_event",{target:event.id,expected_revision:event.revision});assert.equal(publishError,null);assert.ok(version);
console.info("Submitting four requests for one seat...");
const attempts=await Promise.all(Array.from({length:4},(_,i)=>anon.rpc("submit_registration",{event_slug:draft.basics.slug,version,registration_type:type,request:crypto.randomUUID(),name:"Concurrent Demo "+i,email_address:"race"+i+"@example.test",answers:{}})));
const outcomes=attempts.map(x=>{assert.equal(x.error,null);return z.object({reference:z.string().optional(),error:z.string().optional()}).parse(x.data);});
assert.equal(outcomes.filter(x=>x.reference).length,1);
assert.equal(outcomes.filter(x=>x.error==="This registration type is full.").length,3);
console.info("Checking conflicting saves...");
const changes=await Promise.all([db.rpc("save_event",{target:event.id,expected_revision:2,payload:{...draft,basics:{...draft.basics,name:"Draft A"}}}),db.rpc("save_event",{target:event.id,expected_revision:2,payload:{...draft,basics:{...draft.basics,name:"Draft B"}}})]);
console.info(changes.map(x=>({status:x.status,code:x.error?.code,message:x.error?.message})));assert.equal(changes.filter(x=>!x.error).length,1);assert.equal(changes.filter(x=>x.error?.code==="PT409").length,1);
const {data:publicData}=await anon.rpc("public_event",{event_slug:draft.basics.slug});assert.equal(publicEventSchema.parse(publicData).snapshot.name,"Concurrency verification");
await db.auth.signOut({ scope: "local" });console.info("Concurrency verified: exactly one seat allocated, stale draft rejected, public snapshot unchanged.");

